### ISSUE TITLE
Can't open Kanboard tab in redmine -> Page not found

### ISSUE THREAD

**Issue by JSchindele** [hitsumabushi/redmine-kanboard#1]
I was very happy to find this redmine plugin, but unfortunately it does not work for me :-(.
Installation was a little hassle because "circular dependancy"

Circular dependency detected while aCircular dependency detected while autoloading constant RedmineKanboard
/srv/redmine/plugins/redmine_kanboard/lib/redmine_kanboard/issue_wrapper.rb:1:in `<top (required)>'
/srv/redmine/plugins/redmine_kanboard/lib/redmine_kanboard.rb:1:in`<top (required)>'
/srv/redmine/plugins/redmine_kanboard/init.rb:1:in `<top (required)>'
/srv/redmine/lib/redmine/plugin.rb:155:in`block in load'
/srv/redmine/lib/redmine/plugin.rb:146:in `each'
/srv/redmine/lib/redmine/plugin.rb:146:in`load'
/srv/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/srv/redmine/config/environment.rb:14:in`<top (required)>'
utoloading constant RedmineKanboard
/srv/redmine/plugins/redmine_kanboard/lib/redmine_kanboard/issue_wrapper.rb:1:in `<top (required)>'
/srv/redmine/plugins/redmine_kanboard/lib/redmine_kanboard.rb:1:in`<top (required)>'
/srv/redmine/plugins/redmine_kanboard/init.rb:1:in `<top (required)>'
/srv/redmine/lib/redmine/plugin.rb:155:in`block in load'
/srv/redmine/lib/redmine/plugin.rb:146:in `each'
/srv/redmine/lib/redmine/plugin.rb:146:in`load'
/srv/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/srv/redmine/config/environment.rb:14:in`<top (required)>'

Ok when commenting out first line line it worked so far

but when configuring a Project with KanBoard i get
"Page not found 
The page you were trying to access doesn't exist or has been removed.e not found"

Any Ideas ?

My config is :
Environment:
  Redmine version                3.0.1.stable
  Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.14
  Mercurial                      2.7.1
  Cvs                            1.12.12
  Git                            1.8.4.5
  Filesystem  
Redmine plugins:
  kanboards                      0.0.1
  progressive_projects_list      2.0.1
  redmine_agile                  1.3.8
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.1
  redmine_code_review            0.7.0
  redmine_jenkins                1.0-devel
  redmine_lightbox2              0.2.2

**Comment by pslestang** [comment]
Got the same issue, here the log when clicking on kanboard tab:

ActionController::RoutingError (uninitialized constant KanboardsController):
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:230:in `block in constantize'
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:229:in`each'
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:229:in `constantize'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:69:in`controller_reference'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:54:in `controller'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:32:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in`call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in`_run__1346806598036579670__call__888501389544909254__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in`tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in`call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/request_handler.rb:96:in`process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_request_handler.rb:274:in`main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb:206:in `start_request_handler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb:171:in`block in handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:479:in `safe_fork'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb:166:in`handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:180:in `start'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/application_spawner.rb:129:in`start'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:82:in`block in synchronize'
  internal:prelude:10:in `synchronize'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:137:in`spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/share/phusion-passenger/helper-scripts/passenger-spawn-server:99:in`<main>'

**Comment by mrbeaks** [comment]
I have the same problem. Has anyone found a solution?

**Comment by AlroneRhyn** [comment]
Hi Guys, same here, do you get any solution ?

Thx !

**Comment by bmalynovytch** [comment]
Hi guys !

I finally got it working: the plugin needs to be installed in a directory named `kanboards` in the plugins directory, instead of the default name provided by git.
Then run the DB migration `bundle exec rake redmine:plugins:migrate RAILS_ENV=production` and restart Apache or whatever.

The DB migration only worked when the directory was correctly named, even though the plugin was (apparently) loaded in Redmine.

Cheers
