### ISSUE TITLE
Getting this error while installing the plugin for kanboards-v1.2.5

### ISSUE THREAD

**Issue by dm-sanath** [hitsumabushi/redmine-kanboard#4]
Below is my redmine server config.

Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.2.8-p477 (2017-09-14) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

kanboard version is 1.2.5

getting below error even after using redmine-kanboard under kanboards folder.

```
(in /usr/share/redmine)
rake aborted!
Circular dependency detected while autoloading constant RedmineKanboard
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:492:in `load_missing_constant'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/usr/share/redmine/plugins/kanboards/lib/redmine_kanboard/issue_wrapper.rb:1:in `<top (required)>'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/share/redmine/plugins/kanboards/lib/redmine_kanboard.rb:1:in `<top (required)>'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
/usr/share/redmine/plugins/kanboards/init.rb:1:in `<top (required)>'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/share/redmine/lib/redmine/plugin.rb:155:in `block in load'
/usr/share/redmine/lib/redmine/plugin.rb:146:in `each'
/usr/share/redmine/lib/redmine/plugin.rb:146:in `load'
/usr/share/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/usr/share/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.2.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/var/lib/gems/2.2.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

**Comment by ErikasRaginis** [comment]
Have the same issue.

**Comment by npmonteiro** [comment]
Someone solved this issue?
